#!/bin/sh
# Validate one commit message against this repository's convention.
#
# The single source of truth shared by the local `commit-msg` hook (.githooks/commit-msg) and the CI
# check (.github/workflows/commit-lint.yml), so the two can never drift apart.
#
# Usage:
#   lint-commit-message.sh <path-to-message-file>                  # what the hook passes
#   git log -1 --format=%B <sha> | lint-commit-message.sh --ci -    # what CI does, per commit
#
# Options:
#   --ci / --strict   CI mode: reject autosquash placeholders (fixup!/squash!/amend!) rather than
#                     letting them through, since by then there is no rebase left to absorb them.
#
# Exit status: 0 conforming or deliberately exempt, 1 violations found, 2 usage error.
#
# Scope of the check: the header is validated in full, because that is the line read in `git log
# --oneline`, in the commits list, and by whoever prepares a release. Bodies are prose and are left
# alone, apart from the two footer rules where a mistake is silent rather than visible.

set -u

# The Conventional Commits 1.0.0 set. Every type this repository has used is in it.
TYPES='feat|fix|build|chore|ci|docs|perf|refactor|revert|style|test'
TYPES_HUMAN='feat, fix, build, chore, ci, docs, perf, refactor, revert, style, test'

# 72 is where GitHub truncates a subject in its commits list, so a longer header is written but not
# read. Four of the first thirty-seven commits here would have needed trimming; raise this if that
# trade is the wrong way round for you — it is the only knob.
MAX=72

# Unlike the repository this convention was modelled on, scopes are NOT checked against an
# allowlist. There, release tooling partitions commits into independent release trains by scope, so
# an unknown scope silently dropped a commit from a changelog. This package has one train, so an
# allowlist would buy nothing and cost a script edit every time a new area appears. The shape is
# still enforced: lowercase, kebab-case, naming an area and never a file.
SCOPE_SHAPE='[a-z][a-z0-9]*(-[a-z0-9]+)*'

strict=0
case "${1:-}" in
  --ci|--strict) strict=1; shift ;;
  *) ;; # anything else is the message file or '-', handled next
esac

if [ "$#" -lt 1 ] || [ "$1" = "-" ]; then
  msg="$(cat)"
elif [ -f "$1" ]; then
  msg="$(cat "$1")"
else
  printf 'commit-lint: message file not found: %s\n' "$1" >&2
  exit 2
fi

# Strip exactly what git itself strips before recording the message: the scissors block a verbose
# commit appends, and comment lines. An issue reference like "#12" never starts a line, so dropping
# lines that begin with '#' is safe.
msg="$(printf '%s\n' "$msg" | sed -E -e '/^# -+ >8 -+$/,$d' -e '/^#/d')"
subject="$(printf '%s\n' "$msg" | sed -n '1p' | sed 's/[[:space:]]*$//')"

# A merge commit's message is generated by git or GitHub, not written by anyone, so there is nothing
# to hold to a convention. CI filters these out as well, with --no-merges.
case "$subject" in
  'Merge '*) exit 0 ;;
  *) ;;
esac

# An autosquash placeholder is meant to be absorbed by `git rebase --autosquash`, so the hook lets
# it through — refusing it would break the very workflow it belongs to. By the time CI reads the
# pull request the rebase should have happened, so there it is a real error.
case "$subject" in
  'fixup! '*|'squash! '*|'amend! '*)
    if [ "$strict" = 0 ]; then
      exit 0
    fi
    printf 'commit-lint: squash this autosquash placeholder before merge: %s\n' "$subject" >&2
    exit 1
    ;;
  *) ;;
esac

errors=0
errmsgs=''
err() {
  errmsgs="${errmsgs}  - ${1}
"
  errors=$((errors + 1))
  return 0
}

if [ -z "$subject" ]; then
  err "the commit message is empty"
else
  len=${#subject}
  if [ "$len" -gt "$MAX" ]; then
    err "the header is ${len} characters; keep it within ${MAX}"
  fi

  if ! printf '%s' "$subject" | grep -Eq "^(${TYPES})(\(${SCOPE_SHAPE}\))?!?: [a-z]"; then
    # Not well formed. Rather than repeat the grammar, say which part is wrong — the author is
    # looking at a rejected commit, not at a specification. Which four of them try to; the count is
    # taken first so the catch-all below can tell whether any of them managed it.
    before="$errors"

    if ! printf '%s' "$subject" | grep -Eq '^[^:]+: .'; then
      err "expected '<type>[(scope)][!]: <description>' — nothing looks like ': ' after the type"
    fi

    typ="$(printf '%s' "$subject" | sed -E 's/^([a-zA-Z]+).*/\1/')"
    if ! printf '%s' "$typ" | grep -Eq "^(${TYPES})$"; then
      err "unknown type '${typ}' — use one of: ${TYPES_HUMAN}"
    fi

    if printf '%s' "$subject" | grep -Eq '^[a-zA-Z]+\('; then
      scope="$(printf '%s' "$subject" | sed -E 's/^[a-zA-Z]+\(([^)]*)\).*/\1/')"
      if ! printf '%s' "$scope" | grep -Eq "^${SCOPE_SHAPE}$"; then
        err "the scope '${scope}' must be lowercase kebab-case, and must name an area rather than a file"
      fi
    fi

    desc_start="$(printf '%s' "$subject" | sed -E 's/^[^:]*: ?//' | cut -c1)"
    case "$desc_start" in
      [A-Z]) err "the description starts with a capital; write it imperative and lowercase ('add', not 'Add' or 'Added')" ;;
      *) ;;
    esac

    # None of the four recognised the fault, and the header is still one the grammar above rejects.
    # Without this the message accumulates no error at all, falls through to `exit 0`, and both the
    # hook and CI call it conforming — which is what "the header is validated in full" above claimed
    # it could not do. Three that reached it: `feat: 1 add the thing` and `feat: -add the thing`,
    # whose descriptions do not start on a letter, and `feat : add the thing`, whose colon does not
    # follow the type. Each has a colon, a known type, no scope and no capital, so all four looked
    # away. The sentence names the shape rather than the fault, because by here nothing knows it.
    if [ "$errors" -eq "$before" ]; then
      err "expected '<type>[(scope)][!]: <description>', with the description starting on a lowercase letter"
    fi
  fi

  case "$subject" in
    *.) err "the header must not end with a period" ;;
    *) ;;
  esac
fi

# A body glued to the header is invisible in `git log --oneline` and mangled by every tool that
# splits on the first blank line.
nlines="$(printf '%s\n' "$msg" | awk 'END { print NR }')"
line2="$(printf '%s\n' "$msg" | sed -n '2p')"
if [ "$nlines" -ge 2 ] && [ -n "$line2" ]; then
  err "leave a blank line between the header and the body"
fi

# A breaking change is announced twice on purpose: the '!' is what a reader and a tool see in the
# header, the footer is where the migration is written. One without the other means the reader is
# warned with no instructions, or the instructions exist where nobody looks.
prefix="${subject%%: *}"
has_bang=0
case "$prefix" in *!) has_bang=1 ;; *) ;; esac

has_breaking=0
if printf '%s\n' "$msg" | grep -Eq '^BREAKING CHANGE: '; then
  has_breaking=1
fi
if printf '%s\n' "$msg" | grep -Eq '^(BREAKING[-_]CHANGE|[Bb]reaking[ -][Cc]hange):'; then
  err "the breaking-change footer must read exactly 'BREAKING CHANGE:'"
fi
if [ "$has_bang" = 1 ] && [ "$has_breaking" = 0 ]; then
  err "a '!' in the header needs a 'BREAKING CHANGE:' footer describing the migration"
fi
if [ "$has_bang" = 0 ] && [ "$has_breaking" = 1 ]; then
  err "a 'BREAKING CHANGE:' footer needs a '!' before the colon in the header"
fi

if [ "$errors" -gt 0 ]; then
  printf 'commit-lint: this message does not follow the repository convention\n\n%s\n  subject: %s\n' \
    "$errmsgs" "$subject" >&2
  exit 1
fi
exit 0
